name: run
on:
  schedule:
    - cron: "* 5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install sxtwl
    - name: Update test
      run: |
        cd test
        python Schedule.py
